generic-service:
  nameOverride: hmpps-transfer-scheduler-api
  productId: "DPS138" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 1024Mi
    limits:
      cpu: 2048m
      memory: 1280Mi

  image:
    repository: ghcr.io/ministryofjustice/hmpps-transfer-scheduler-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-transfer-scheduler-api-cert
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "H2C"
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        more_set_headers "Strict-Transport-Security: \"max-age=31536000; includeSubDomains; preload\"";

  # Used to access resources like S3 buckets, SQS queues and SNS topics
  serviceAccountName: hmpps-transfer-scheduler-api


  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JDK_JAVA_OPTIONS: "-Xmx512m -XX:+UseG1GC"
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException,org.springframework.web.servlet.resource.NoResourceFoundException,org.springframework.web.context.request.async.AsyncRequestNotUsableException"

  namespace_secrets:
    hmpps-transfer-scheduler-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-transfer-scheduler-api-sentry:
      SENTRY_DSN: SENTRY_DSN
      SENTRY_AUTH_TOKEN: SENTRY_AUTH_TOKEN
    hmpps-transfer-scheduler-api-client-creds:
      CLIENT_ID: "API_CLIENT_ID"
      CLIENT_SECRET: "API_CLIENT_SECRET"
    hmpps-transfer-scheduler-postgres:
      DB_SERVER: "database_server"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    domain-events-queue-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "queue_name"
    domain-events-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "queue_name"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  retryDlqCronjob:
    enabled: true
    retryDlqSchedule: "0/30 7-19 * * 1-5"

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5'
    shutdown: '30 21 * * 1-5'
    timeZone: Europe/London
    retryDlqSchedule: "0/30 7-19 * * 1-5"

generic-prometheus-alerts:
  targetApplication: hmpps-transfer-scheduler-api
